### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Omi0** [ibuioli/ngFacetracker#1]
It refers to jsfeat module. Do you experience the same problem. Coz I experience exactly the same problem when I am trying to run clmtrackr examples.

**Comment by ibuioli** [comment]
Yes, I am experimenting that issue since Angular 7, with Angular 6 it works. I will check in the near future but It seem a problem with the module compatibility.

**Comment by ibuioli** [comment]
The problem was a bad load of CLMTrackr. Now its loaded with angular.json like CommonJS Module. The repository is update. Close.
